In [6]:
import numpy as numpy
import pandas as pd
import seaborn as sns
import plotly as plt

In [4]:
ratings = pd.read_csv('datos/movie_ratings42.csv').set_index('Movie')

In [5]:
ratings

Brandon  Emily  Cleo  Rusty  \
Movie                                                                      
Aquaman                                            4      1     2      2   
Avengers: Infinity War                             2      5     2      5   
Black Panther                                      5      2     5      1   
Bohemian Rhapsody                                  2      3     4      4   
Deadpool 2                                         3      2     4      5   
Fantastic Beasts: The Crimes of Grindelwald        5      4     1      2   
Incredibles 2                                      4      2     3      4   
Jurassic World: Fallen Kingdom                     2      3     5      4   
Mission: Impossible – Fallout                      5      5     4      3   
Venom                                              4      1     4      5   

                                             Samantha  
Movie                                                  
Aquaman                                             2  
Avengers: Infinity War                              5  
Black Panther                                       1  
Bohemian Rhapsody                                   1  
Deadpool 2                                          1  
Fantastic Beasts: The Crimes of Grindelwald         5  
Incredibles 2                                       4  
Jurassic World: Fallen Kingdom                      5  
Mission: Impossible – Fallout                       2  
Venom                                               2

In [ ]:
def ploteado(peli1,peli2):
    x=ratings.T[peli1]
    y=ratings.T[peli2]

    n= list(ratings.columns)

    plt.figure

In [7]:
ratings.T

Movie     Aquaman  Avengers: Infinity War  Black Panther  Bohemian Rhapsody  \
Brandon         4                       2              5                  2   
Emily           1                       5              2                  3   
Cleo            2                       2              5                  4   
Rusty           2                       5              1                  4   
Samantha        2                       5              1                  1   

Movie     Deadpool 2  Fantastic Beasts: The Crimes of Grindelwald  \
Brandon            3                                            5   
Emily              2                                            4   
Cleo               4                                            1   
Rusty              5                                            2   
Samantha           1                                            5   

Movie     Incredibles 2  Jurassic World: Fallen Kingdom  \
Brandon               4                               2   
Emily                 2                               3   
Cleo                  3                               5   
Rusty                 4                               4   
Samantha              4                               5   

Movie     Mission: Impossible – Fallout  Venom  
Brandon                               5      4  
Emily                                 5      1  
Cleo                                  4      4  
Rusty                                 3      5  
Samantha                              2      2

In [ ]:
from scipy.spatial.distance import pdist, squareform
#pdist calcula distancia en varios planos
#square aplana todo

In [9]:
pdist(ratings.T,'euclidean') #calcula la distancia de todas las pelis de todas las personas

array([6.63324958, 6.        , 7.41619849, 7.48331477, 6.92820323,
       6.40312424, 5.09901951, 5.56776436, 8.24621125, 6.70820393])

In [10]:
distancias = squareform(pdist(ratings.T,'euclidean'))

In [11]:
distancias

array([[0.        , 6.63324958, 6.        , 7.41619849, 7.48331477],
       [6.63324958, 0.        , 6.92820323, 6.40312424, 5.09901951],
       [6.        , 6.92820323, 0.        , 5.56776436, 8.24621125],
       [7.41619849, 6.40312424, 5.56776436, 0.        , 6.70820393],
       [7.48331477, 5.09901951, 8.24621125, 6.70820393, 0.        ]])

In [12]:
similitud = 1/(1+distancias)
similitud

array([[1.        , 0.1310058 , 0.14285714, 0.11881849, 0.11787845],
       [0.1310058 , 1.        , 0.12613198, 0.13507811, 0.16396078],
       [0.14285714, 0.12613198, 1.        , 0.15225881, 0.10815241],
       [0.11881849, 0.13507811, 0.15225881, 1.        , 0.12973191],
       [0.11787845, 0.16396078, 0.10815241, 0.12973191, 1.        ]])

In [13]:
pd.DataFrame(similitud,columns=ratings.columns, index=ratings.columns)

Brandon     Emily      Cleo     Rusty  Samantha
Brandon   1.000000  0.131006  0.142857  0.118818  0.117878
Emily     0.131006  1.000000  0.126132  0.135078  0.163961
Cleo      0.142857  0.126132  1.000000  0.152259  0.108152
Rusty     0.118818  0.135078  0.152259  1.000000  0.129732
Samantha  0.117878  0.163961  0.108152  0.129732  1.000000

In [14]:
ratings.T.columns

Index(['Aquaman', 'Avengers: Infinity War', 'Black Panther',
       'Bohemian Rhapsody', 'Deadpool 2',
       'Fantastic Beasts: The Crimes of Grindelwald', 'Incredibles 2',
       'Jurassic World: Fallen Kingdom', 'Mission: Impossible – Fallout',
       'Venom'],
      dtype='object', name='Movie')

In [15]:
rodri = {'Aquaman':4,
         'Avengers: Infinity War':3,
         'Black Panther': 1,
         'Bohemian Rhapsody':5, 
         'Deadpool 2':4,
       'Fantastic Beasts: The Crimes of Grindelwald':3,
        'Incredibles 2':2,
       'Jurassic World: Fallen Kingdom':3, 
       'Mission: Impossible – Fallout':2,
       'Venom':1}

In [16]:
ratings['Rodri'] = pd.Series(rodri)

ratings

Brandon  Emily  Cleo  Rusty  \
Movie                                                                      
Aquaman                                            4      1     2      2   
Avengers: Infinity War                             2      5     2      5   
Black Panther                                      5      2     5      1   
Bohemian Rhapsody                                  2      3     4      4   
Deadpool 2                                         3      2     4      5   
Fantastic Beasts: The Crimes of Grindelwald        5      4     1      2   
Incredibles 2                                      4      2     3      4   
Jurassic World: Fallen Kingdom                     2      3     5      4   
Mission: Impossible – Fallout                      5      5     4      3   
Venom                                              4      1     4      5   

                                             Samantha  Rodri  
Movie                                                         
Aquaman                                             2      4  
Avengers: Infinity War                              5      3  
Black Panther                                       1      1  
Bohemian Rhapsody                                   1      5  
Deadpool 2                                          1      4  
Fantastic Beasts: The Crimes of Grindelwald         5      3  
Incredibles 2                                       4      2  
Jurassic World: Fallen Kingdom                      5      3  
Mission: Impossible – Fallout                       2      2  
Venom                                               2      1

In [17]:
distancias = squareform(pdist(ratings.T,'euclidean'))
similitud = 1/(1+distancias)
pd.DataFrame(similitud,columns=ratings.columns, index=ratings.columns)

Brandon     Emily      Cleo     Rusty  Samantha     Rodri
Brandon   1.000000  0.131006  0.142857  0.118818  0.117878  0.119782
Emily     0.131006  1.000000  0.126132  0.135078  0.163961  0.150221
Cleo      0.142857  0.126132  1.000000  0.152259  0.108152  0.131006
Rusty     0.118818  0.135078  0.152259  1.000000  0.129732  0.148268
Samantha  0.117878  0.163961  0.108152  0.129732  1.000000  0.128496
Rodri     0.119782  0.150221  0.131006  0.148268  0.128496  1.000000

In [19]:
rating_new = pd.read_csv('datos/movie_ratings_sinrodri.csv').set_index('Movie')

Proceso pendiente

In [20]:
import pickle

In [22]:
with open('datos/metadata_clean_alumnos.pkl', 'rb') as archivo:
    metadata = pickle.load(archivo)

In [23]:
metadata.head()

id  popularity  imbd_mean                        title  \
0    862   21.946943   3.888157                    Toy Story   
1   8844   17.015539   3.236953                      Jumanji   
2  15602   11.712900   3.175550             Grumpier Old Men   
3  31357    3.859495   2.875713            Waiting to Exhale   
4  11862    8.387519   3.079565  Father of the Bride Part II   

                                             tags_v2  
0  animation comedy family jealousy toy boy frien...  
1  adventure fantasy family board game disappeara...  
2  romance comedy fishing best friend duringcredi...  
3  comedy drama romance based on novel interracia...  
4  comedy baby midlife crisis confidence aging da...

In [24]:
with open('datos/ratings_merge.pkl', 'rb') as archivo:
    ratings_merge_df = pickle.load(archivo)

In [25]:
ratings_merge_df.head()

userId  movieId  rating   timestamp  imdbId  tmdbId
0       1      110     1.0  1425941529  112573     197
1      11      110     3.5  1231676989  112573     197
2      22      110     5.0  1111937009  112573     197
3      24      110     5.0   979870012  112573     197
4      29      110     3.0  1044020005  112573     197

## Preparar

In [ ]:
metadata_final = metadata.merge(ratings_merge_df, left_on='id', right_on='')