<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introducción" data-toc-modified-id="Introducción-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introducción</a></span></li><li><span><a href="#¿Qué-es-NumPy?" data-toc-modified-id="¿Qué-es-NumPy?-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>¿Qué es NumPy?</a></span></li><li><span><a href="#¿Qué-es-un-array?" data-toc-modified-id="¿Qué-es-un-array?-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>¿Qué es un <em>array</em>?</a></span></li><li><span><a href="#Creación-de-arrays" data-toc-modified-id="Creación-de-arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Creación de <em>arrays</em></a></span><ul class="toc-item"><li><span><a href="#Crear-un-array-a-partir-de-una-lista" data-toc-modified-id="Crear-un-array-a-partir-de-una-lista-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Crear un array a partir de una lista</a></span></li><li><span><a href="#Crear-un-array-vacío" data-toc-modified-id="Crear-un-array-vacío-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Crear un array vacío</a></span></li><li><span><a href="#Crear-un-array-de-ceros" data-toc-modified-id="Crear-un-array-de-ceros-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Crear un array de ceros</a></span></li><li><span><a href="#Crear-un-array-de-unos" data-toc-modified-id="Crear-un-array-de-unos-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Crear un array de unos</a></span></li><li><span><a href="#Crear-un-array-con-valores-secuenciales" data-toc-modified-id="Crear-un-array-con-valores-secuenciales-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Crear un array con valores secuenciales</a></span></li><li><span><a href="#Crear-un-array-usando-random" data-toc-modified-id="Crear-un-array-usando-random-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Crear un array usando random</a></span><ul class="toc-item"><li><span><a href="#np.random.randint" data-toc-modified-id="np.random.randint-4.6.1"><span class="toc-item-num">4.6.1&nbsp;&nbsp;</span>np.random.randint</a></span></li><li><span><a href="#np.random.rand" data-toc-modified-id="np.random.rand-4.6.2"><span class="toc-item-num">4.6.2&nbsp;&nbsp;</span>np.random.rand</a></span></li><li><span><a href="#np.random.random_sample" data-toc-modified-id="np.random.random_sample-4.6.3"><span class="toc-item-num">4.6.3&nbsp;&nbsp;</span>np.random.random_sample</a></span></li></ul></li></ul></li><li><span><a href="#Indexación" data-toc-modified-id="Indexación-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Indexación</a></span><ul class="toc-item"><li><span><a href="#Indexación-en-arrays-unidimensionales" data-toc-modified-id="Indexación-en-arrays-unidimensionales-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Indexación en <em>arrays</em> unidimensionales</a></span></li><li><span><a href="#Indexación-en-arrays-bidimensionales" data-toc-modified-id="Indexación-en-arrays-bidimensionales-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Indexación en <em>arrays</em> bidimensionales</a></span></li><li><span><a href="#Indexación-en-arrays-tridimensionales" data-toc-modified-id="Indexación-en-arrays-tridimensionales-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Indexación en <em>arrays</em> tridimensionales</a></span></li></ul></li><li><span><a href="#Filtrado-de-datos-en-arrays" data-toc-modified-id="Filtrado-de-datos-en-arrays-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Filtrado de datos en <em>arrays</em></a></span><ul class="toc-item"><li><span><a href="#Filtrado-con-condiciones" data-toc-modified-id="Filtrado-con-condiciones-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Filtrado con condiciones</a></span></li><li><span><a href="#Filtrado-con-np.where()" data-toc-modified-id="Filtrado-con-np.where()-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Filtrado con <code>np.where()</code></a></span></li></ul></li><li><span><a href="#Operaciones-aritméticas-con-arrays" data-toc-modified-id="Operaciones-aritméticas-con-arrays-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Operaciones aritméticas con <em>arrays</em></a></span></li><li><span><a href="#Funciones-universales-o-ufuncs" data-toc-modified-id="Funciones-universales-o-ufuncs-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Funciones universales o <code>ufuncs</code></a></span><ul class="toc-item"><li><span><a href="#Operaciones-estadísticas" data-toc-modified-id="Operaciones-estadísticas-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Operaciones estadísticas</a></span><ul class="toc-item"><li><span><a href="#np.mean()" data-toc-modified-id="np.mean()-8.1.1"><span class="toc-item-num">8.1.1&nbsp;&nbsp;</span><code>np.mean()</code></a></span></li><li><span><a href="#np.var()" data-toc-modified-id="np.var()-8.1.2"><span class="toc-item-num">8.1.2&nbsp;&nbsp;</span><code>np.var()</code></a></span></li><li><span><a href="#np.std()" data-toc-modified-id="np.std()-8.1.3"><span class="toc-item-num">8.1.3&nbsp;&nbsp;</span><code>np.std()</code></a></span></li></ul></li><li><span><a href="#Operaciones-aritméticas" data-toc-modified-id="Operaciones-aritméticas-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Operaciones aritméticas</a></span><ul class="toc-item"><li><span><a href="#np.min()" data-toc-modified-id="np.min()-8.2.1"><span class="toc-item-num">8.2.1&nbsp;&nbsp;</span><code>np.min()</code></a></span></li><li><span><a href="#np.max()" data-toc-modified-id="np.max()-8.2.2"><span class="toc-item-num">8.2.2&nbsp;&nbsp;</span><code>np.max()</code></a></span></li><li><span><a href="#np.sum()" data-toc-modified-id="np.sum()-8.2.3"><span class="toc-item-num">8.2.3&nbsp;&nbsp;</span><code>np.sum()</code></a></span></li></ul></li><li><span><a href="#Otros-métodos" data-toc-modified-id="Otros-métodos-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>Otros métodos</a></span><ul class="toc-item"><li><span><a href="#np.sort()" data-toc-modified-id="np.sort()-8.3.1"><span class="toc-item-num">8.3.1&nbsp;&nbsp;</span><code>np.sort()</code></a></span></li><li><span><a href="#np.transpose()" data-toc-modified-id="np.transpose()-8.3.2"><span class="toc-item-num">8.3.2&nbsp;&nbsp;</span><code>np.transpose()</code></a></span><ul class="toc-item"><li><span><a href="#Unidimensional" data-toc-modified-id="Unidimensional-8.3.2.1"><span class="toc-item-num">8.3.2.1&nbsp;&nbsp;</span>Unidimensional</a></span></li><li><span><a href="#Bidimensional" data-toc-modified-id="Bidimensional-8.3.2.2"><span class="toc-item-num">8.3.2.2&nbsp;&nbsp;</span>Bidimensional</a></span></li><li><span><a href="#Multidimensional" data-toc-modified-id="Multidimensional-8.3.2.3"><span class="toc-item-num">8.3.2.3&nbsp;&nbsp;</span>Multidimensional</a></span></li></ul></li></ul></li><li><span><a href="#reshape():" data-toc-modified-id="reshape():-8.4"><span class="toc-item-num">8.4&nbsp;&nbsp;</span><code>reshape()</code>:</a></span></li><li><span><a href="#np.swapaxes()" data-toc-modified-id="np.swapaxes()-8.5"><span class="toc-item-num">8.5&nbsp;&nbsp;</span><code>np.swapaxes()</code></a></span></li></ul></li></ul></div>


# Introducción 

Hasta ahora, en el bootcamp, hemos cubierto los conceptos básicos de programación en el módulo 1 y hemos explorado el proceso de extracción de datos utilizando herramientas de web scraping en Python y SQL en el módulo 2. Ahora, es el momento de continuar con el flujo de trabajo de un analista de datos y adentrarnos en la transformación de los datos.


En este módulo vamos a abordar un aspecto fundamental para cualquier analista de datos: la transformación de los datos. La transformación de datos es un proceso esencial en el campo del análisis de datos, ya que permite convertir los datos brutos en información procesable y significativa, es decir, nos permite convertir los datos sin procesar en una forma que sea más útil y significativa para nuestros análisis. A medida que avanzamos en este módulo, aprenderemos técnicas y herramientas para manipular, limpiar y estructurar los datos de manera eficiente. Una vez que hemos extraído los datos, es posible que nos encontremos con diversos desafíos, como datos duplicados, formatos inconsistentes, valores faltantes o incoherencias. La transformación de datos nos brinda la capacidad de abordar estos desafíos mediante la aplicación de técnicas de limpieza y normalización. Podremos eliminar duplicados, corregir errores, estandarizar formatos y completar valores faltantes para asegurarnos de que nuestros datos sean precisos y confiables. Además de la limpieza y normalización, la transformación de datos también implica la creación de nuevas variables o características derivadas que puedan ayudarnos a obtener una comprensión más profunda de los datos. Podemos aplicar funciones matemáticas, realizar cálculos estadísticos o combinar variables existentes para generar nuevas perspectivas y descubrir patrones ocultos en los datos.

Al finalizar esta etapa de transformación, nuestros datos estarán preparados y listos para la etapa de análisis propiamente dicha. La transformación adecuada de los datos no solo garantiza la calidad y confiabilidad de nuestros resultados, sino que también nos permite extraer información valiosa y tomar decisiones basadas en datos con mayor precisión.


# ¿Qué es NumPy?

**NumPy**, que significa "Numerical Python" (Python Numérico), es una biblioteca de Python muy popular y poderosa utilizada principalmente para el procesamiento numérico y científico de datos. Proporciona soporte para matrices multidimensionales, junto con una amplia colección de funciones matemáticas para operar en estas matrices.

La principal característica de **NumPy** es el objeto de matriz, llamado `array` o `ndarray` (abreviatura de "n-dimensional array" o "matriz n-dimensional"). Estas matrices son similares a las listas en Python, pero ofrecen muchas más capacidades y eficiencia para operaciones numéricas. Las matrices **NumPy** pueden tener hasta N dimensiones y **contienen elementos del mismo tipo de datos**, lo que permite un cálculo rápido y eficiente.

Aquí hay algunas características clave de **NumPy**:

1. **Funciones matemáticas eficientes**: NumPy proporciona una amplia gama de funciones matemáticas incorporadas, como trigonométricas, exponenciales, logarítmicas, algebraicas, estadísticas, entre otras. Estas funciones se pueden aplicar a matrices completas sin la necesidad de escribir bucles explícitos, lo que facilita y acelera el cálculo.

2. **Operaciones vectorizadas**: Las operaciones vectorizadas son una forma eficiente de realizar cálculos en matrices sin necesidad de bucles. NumPy permite realizar operaciones matemáticas y lógicas directamente en matrices enteras, lo que resulta en un código más compacto y rápido.

3. **Broadcasting**:  Es una poderosa funcionalidad de **NumPy** que permite realizar operaciones entre matrices de diferentes formas y tamaños. **NumPy** automáticamente ajusta las formas de las matrices para que sean compatibles y realiza las operaciones de manera eficiente.

4. **Integración con otras bibliotecas**: **NumPy** se utiliza ampliamente en el ecosistema científico de Python y se integra con otras bibliotecas populares como SciPy (biblioteca para computación científica), Matplotlib (para visualización de datos) y Pandas (para análisis de datos).

> **NumPy** es una biblioteca fundamental para el procesamiento numérico en Python. Su uso eficiente de memoria y sus operaciones vectorizadas hacen que sea una opción ideal para realizar cálculos numéricos y científicos, especialmente cuando se trabaja con grandes conjuntos de datos o se requiere un alto rendimiento computacional.


📌 **NOTA** Antes de ponernos a trabajar con NumPy tendremos que instalar la librería, para eso lo que tendremos que hacer es escribir en la terminal la siguiente línea de código.
```bash
!pip install numpy
```

# ¿Qué es un *array*?

Un *array*, también conocido como matriz o arreglo, es una estructura de datos que permite almacenar una colección de elementos del mismo tipo. Los *arrays* son utilizados para organizar y manipular conjuntos de datos de manera eficiente. En un *array*, los elementos están dispuestos en una secuencia ordenada y se accede a ellos mediante un índice. Al igual que hacíamos en listas, la indexación comienza en 0. 

Los *arrays* pueden tener una o varias dimensiones. Un *array* unidimensional se representa como una secuencia lineal de elementos, similar a una lista en Python. Por ejemplo:

```
[1, 2, 3, 4, 5]
```

Un array bidimensional se organiza en filas y columnas, formando una especie de tabla o matriz. Cada elemento en un *array* bidimensional se identifica mediante dos índices: uno para la fila y otro para la columna. Por ejemplo:

```python
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

# si quisieras acceder al número 5 tendrías que elegir la fila 2 y la columna 2, como los índices en python empiezan en 0, los índices que tendrías que usar son: 
[1][1] # esto nos devolvería el valor 5. 
```

Los *arrays* pueden tener más dimensiones, como los *arrays* tridimensionales, cuatridimensionales, y así sucesivamente. Estas estructuras de datos multidimensionales son útiles para representar y manipular datos más complejos, como imágenes, volúmenes de datos científicos, tensores en aprendizaje automático, entre otros, aspectos que nosotras no trabajaremos normalente como analistas.

# Creación de *arrays*

NumPy permite crear *arrays* de distintas formas las más comunes son:

1. **Crear un array a partir de una lista**: Puedes crear un *array* NumPy a partir de una lista utilizando la función `np.array()`.

2. **Crear un array vacío**: Puedes crear un *array* vacío especificando la forma deseada utilizando la función `np.empty()`. Debemos tener en cuenta que los valores del array vacío pueden ser impredecibles, ya que toman los valores almacenados en la memoria en ese momento.

3. **Crear un array de ceros**: Puedes crear un *array* con todos los elementos establecidos en cero utilizando la función `np.zeros()`. 

4. **Crear un array de unos**: Puedes crear un *array* con todos los elementos establecidos en uno utilizando la función `np.ones()`.

5. **Crear un array con valores secuenciales**: Puedes crear un *array* con valores secuenciales utilizando la función `np.arange()`. 

6. **Crear un array usando random de NumPy**: Puedes crear un *array* con números aleatorios usando distintos métodos de `random` en NumPy


In [15]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

## Crear un array a partir de una lista

In [16]:
print("-------------ARRAY UNIDIMENSIONAL--------------")
# definimos una lista que usaremos para convertir en array unidimensional
lista = [1, 2, 3, 4, 5]
print("La lista a partir de la que crearemos un array unidimensional es:", lista)

# convertimos la lista en array usando el método 'np.array()' 
array_unidimensional = np.array(lista)
print(f"El array unidimensional creado a partir de la lista es: \n  {array_unidimensional} \n")




print("-------------ARRAY BIDIMENSIONAL--------------")
# para crear un array bidimensional necesitaremos una lista de listas
lista_listas = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
print("La lista de listas a partir de la que crearemos un array bidimensional es:", lista_listas)

# convertimos la lista en array usando el método 'np.array()' 
# 📌 fijaos como ahora el array que hemos construido tiene "filas" y "columnas"
array_bidimensional = np.array(lista_listas)
print(f"El array bidimensional creado a partir de la lista es:\n  {array_bidimensional}\n")




print("-------------ARRAY TRIDIMENSIONAL--------------")
# para crear un array tridimensional necesitaremos una lista de listas de listas 🤯. 
lista_listas_listas = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]]
print("La lista de listas de listas a partir de la que crearemos un array tridimensional es:", lista_listas_listas)

# convertimos la lista en array usando el método 'np.array()' 
# fijaos como ahora el array que hemos construido tiene "filas" y "columnas"
array_tridimensional = np.array(lista_listas_listas)
print(f"El array tridimensional creado a partir de la lista es:\n  {array_tridimensional}\n")



-------------ARRAY UNIDIMENSIONAL--------------
La lista a partir de la que crearemos un array unidimensional es: [1, 2, 3, 4, 5]
El array unidimensional creado a partir de la lista es: 
  [1 2 3 4 5] 

-------------ARRAY BIDIMENSIONAL--------------
La lista de listas a partir de la que crearemos un array bidimensional es: [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
El array bidimensional creado a partir de la lista es:
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

-------------ARRAY TRIDIMENSIONAL--------------
La lista de listas de listas a partir de la que crearemos un array tridimensional es: [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]]
El array tridimensional creado a partir de la lista es:
  [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]



Acabamos de aprender a crear *arrays* de distintas dimensiones, y como vemos en el print anterior vemos que tienen distintas formas, pero solo podemos decir eso. Exploremos ahora, con una serie de métodos específicos, cuales son las propiedades de cada uno de estos *arrays* para entender mejor sus diferencias. 

NumPy ofrece una variedad de métodos útiles para comprender y explorar las propiedades de un *array*. Veamos los más importantes:

1. **Forma del array**: El método `shape` devuelve una tupla que representa la forma (dimensiones) del *array*. Cada elemento de la tupla representa el tamaño de una dimensión. 

2. **Número de dimensiones**: El atributo `ndim` devuelve el número de dimensiones del *array*.

3. **Tamaño total del array**: El atributo `size` devuelve el número total de elementos en el *array*. 


4. **Tipo de datos del array**: El atributo `dtype` devuelve el tipo de datos de los elementos del *array*. 


In [17]:
print("-------------ARRAY UNIDIMENSIONAL--------------")
print(f"El array unidimensional es: \n  {array_unidimensional}")
print(f"La forma del array unidimensional es: {array_unidimensional.shape}")
print(f"El número de dimensiones del array unidimensional es: {array_unidimensional.ndim}")
print(f"El número de elementos del array unidimensional es: {array_unidimensional.size}")
print(f"El tipo de dato que tenemos en el array unidimensional es: {array_unidimensional.dtype}\n")

-------------ARRAY UNIDIMENSIONAL--------------
El array unidimensional es: 
  [1 2 3 4 5]
La forma del array unidimensional es: (5,)
El número de dimensiones del array unidimensional es: 1
El número de elementos del array unidimensional es: 5
El tipo de dato que tenemos en el array unidimensional es: int64



Entendamos los resultados que hemos obtenido en la celda anterior: 

- ***array* unidimensional**

    - *Forma*: el método `shape` nos devuelve una tupla donde nos va indicar el número de elementos que tenemos por cada dimensión que tiene nuestro *array*. En este caso, nos devuelve una tupla de un solo elemento porque solo tenemos una dimensión que tiene 5 elementos. 

    - *Número de dimensiones*: para entender bien que es lo que nos devuelve el atributo `ndim` necesitamos comprender que es una dimensión en el contexto de un *array*. En términos simples, una dimensión en un *array* se refiere a la cantidad de índices necesarios para acceder a un elemento dentro del *array*. Por ejemplo, un *array* unidimensional requiere un solo índice para acceder a un elemento, mientras que un *array* bidimensional requiere dos índices (uno para la fila y otro para la columna). Entendiendo esto,  y pensando que la indexación en *arrays* es como en las listas, en nuestro caso solo necesitamos un índice para acceder a algún valor dentro del *array*, por lo que la dimensión de este *array* es de 1

    - *Número de elementos*: con el atributo `size` nos dice el número de elementos que  hay dentro del *array*, en este caso tenemos 5 números enteros

    - *Tipo de datos*: usando el atributo `dtype` conocemos que  el *array* esta compuesto por elementos de tipo *integer*. Recordad que en un *array* todos los elementos deben ser del mismo tipo. 


In [18]:
print("-------------ARRAY BIDIMENSIONAL--------------")
print(f"El array bidimensional es: \n  {array_bidimensional}")
print(f"La forma del array bidimensional es: {array_bidimensional.shape}")
print(f"El número de dimensiones del array bidimensional es: {array_bidimensional.ndim}")
print(f"El número de elementos del array bidimensional es: {array_bidimensional.size}")
print(f"El tipo de dato que tenemos en el array bidimensional es: {array_bidimensional.dtype}\n")

-------------ARRAY BIDIMENSIONAL--------------
El array bidimensional es: 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
La forma del array bidimensional es: (2, 5)
El número de dimensiones del array bidimensional es: 2
El número de elementos del array bidimensional es: 10
El tipo de dato que tenemos en el array bidimensional es: int64



Entendamos los resultados que hemos obtenido en la celda anterior: 


- ***array* bidimensional**

    - *Forma*: en este caso la tupla esta compuesta por dos valores, podríamos decir que tenemos "filas" y "columnas". En concreto nos esta diciendo que tenemos 2 filas y 5 columnas. 

    - *Número de dimensiones*: En este caso necesitamos dos índices para acceder a algún valor dentro del *array*, por lo que la dimensión de este *array* es de 2. Es como acceder a un elemento en una lista de listas

    - *Número de elementos*: con el atributo `size` nos dice el número de elementos que  hay dentro del *array*, en este caso tenemos 10 números enteros

    - *Tipo de datos*: usando el atributo `dtype` conocemos que  el *array* esta compuesto por elementos de tipo *integer*. Recordad que en un *array* todos los elementos deben ser del mismo tipo. 


In [19]:
print("-------------ARRAY TRIDIMENSIONAL--------------")
print(f"El array tridimensional es: \n  {array_tridimensional}")
print(f"La forma del array tridimensional es: {array_tridimensional.shape}")
print(f"El número de dimensiones del array tridimensional es: {array_tridimensional.ndim}")
print(f"El número de elementos del array tridimensional es: {array_tridimensional.size}")
print(f"El tipo de dato que tenemos en el array tridimensional es: {array_tridimensional.dtype}\n")

-------------ARRAY TRIDIMENSIONAL--------------
El array tridimensional es: 
  [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
La forma del array tridimensional es: (2, 2, 5)
El número de dimensiones del array tridimensional es: 3
El número de elementos del array tridimensional es: 20
El tipo de dato que tenemos en el array tridimensional es: int64



Entendamos los resultados que hemos obtenido en la celda anterior: 

- ***array* tridimensional**

    - *Forma*: en este caso la tupla esta compuesta por tres valores. Esto lo podemos interpretar de la siguiente forma, tenemos 3 dimensiones, la primera hace referencia al número de *arrays* más pequeños que tenemos en nuestro *array* principal (en este caso 2, es decir, tenemos dos *arrays*). Luego tenemos dos valores más que son el 2 y el 5 que indican que cada uno de los *arrays* pequeños tienen dos filas y 5 columnas. 

    - *Número de dimensiones*: En este caso necesitamos tres índices para acceder a algún valor dentro del *array*, por lo que la dimensión de este *array* es de 3. 

    - *Número de elementos*: con el atributo `size` nos dice el número de elementos que  hay dentro del *array*, en este caso tenemos 20 números enteros

    - *Tipo de datos*: usando el atributo `dtype` conocemos que  el *array* esta compuesto por elementos de tipo *integer*. Recordad que en un *array* todos los elementos deben ser del mismo tipo. 


Comprendiendo las diferencias entre los distintos tipos de *arrays* y sus propiedades, sigamos viendo otras formas de crear **arrays**. 

## Crear un array vacío

Al igual que en el caso anterior, podremos crear *arrays* vacíos de distintas dimensiones. Su sintaxis básica es:


```python
np.empty(shape, dtype=float)
```
- `shape`: Especifica la forma (dimensiones) del *array* que se creará. Puede ser un entero, una tupla de enteros o una lista de enteros. 

- `dtype` (opcional): Especifica el tipo de datos de los elementos del *array*. Por defecto, es `float`, lo que significa que los elementos del *array* serán números de punto flotante. También se pueden especificar otros tipos de datos, como `int` para números enteros, `bool` para valores booleanos, `str` para cadenas de texto, entre otros.


Aquí tienes algunos ejemplos de cómo utilizar `np.empty`:

```python
import numpy as np

# Crear un array vacío de 2 filas y 3 columnas
array_vacio = np.empty((2, 3))
print(array_vacio)

# Crear un array vacío de forma (4, )
array_vacio_1D = np.empty(4)
print(array_vacio_1D)
```

El método `np.empty` crea un *array* vacío sin inicializar sus elementos. Esto significa que los valores de los elementos pueden ser impredecibles y dependerán de los datos almacenados previamente en la memoria.

In [20]:
print("------------- ARRAY UNIDIMENSIONAL VACÍO --------------")
# creamos el array vacío unidimensional especificando el número de elementos que queremos tener en el array. 
# como solo tiene una dimensión solo le paso un valor. Nos genera un array con 4 valores.
array_vacio_unidimensional =  np.empty(4)
print(f"El array unidimensional creado a partir del método np.emtpy(): \n  {array_vacio_unidimensional} \n")

------------- ARRAY UNIDIMENSIONAL VACÍO --------------
El array unidimensional creado a partir del método np.emtpy(): 
  [6.23042070e-307 4.67296746e-307 1.69121096e-306 8.35425485e-309] 



In [21]:
print("------------- ARRAY BIDIMENSIONAL VACÍO --------------")
# creamos el array vacío bidimensional especificando el número de elementos que queremos tener en el array. 
# como en este caso queremos tener dos dimensiones, le tendremos que pasar dos valores, con el número de elementos que queremos en cada una de ellas
# el primer valor hace referencia al número de filas y el segundo al número de columnas
array_vacio_bidimensional =  np.empty((4,2))
print(f"El array bidimensional creado a partir del método np.emtpy(): \n  {array_vacio_bidimensional} \n")


------------- ARRAY BIDIMENSIONAL VACÍO --------------
El array bidimensional creado a partir del método np.emtpy(): 
  [[0.0000e+000 0.0000e+000]
 [0.0000e+000 0.0000e+000]
 [0.0000e+000 1.2035e-320]
 [0.0000e+000 0.0000e+000]] 



In [22]:
print("------------- ARRAY TRIDIMENSIONAL VACÍO --------------")
# creamos el array vacío tridimensional especificando el número de elementos que queremos tener en el array. 
# queremos tener tres dimensiones, por lo que le tendremos que pasar tres valores, con el número de elementos que queremos en cada una de ellas
# el primer valor hace referencia al número de arrays "pequeños" que queremos, el segundo al número de filas y el último al número de columnas
array_vacio_tridimensional =  np.empty((3, 4, 2)) # estamos generando un array de tres matrices donde cada una de ellas tienen 4 filas y 2 columnas
print(f"El array tridimensional creado a partir del método np.emtpy(): \n  {array_vacio_tridimensional} \n")

------------- ARRAY TRIDIMENSIONAL VACÍO --------------
El array tridimensional creado a partir del método np.emtpy(): 
  [[[ 6.95275545e-310  6.95275545e-310]
  [ 6.95275545e-310  6.95275545e-310]
  [ 6.95275545e-310  6.95275545e-310]
  [ 1.02274000e-311  1.02273994e-311]]

 [[ 4.94065646e-324  6.95275545e-310]
  [ 1.84115564e-314  7.48294317e+012]
  [-3.42843178e+186  2.12199579e-314]
  [ 6.95275545e-310  9.73480423e-309]]

 [[ 0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  1.11253693e-308]]] 



## Crear un array de ceros

Permite crear un *array* compuesto solo por 0. La sintaxis del método `np.zeros` en NumPy es la siguiente:

```python
np.zeros(shape, dtype=float)
```

- `shape`: Especifica la forma (dimensiones) del *array* que se creará. Puede ser un entero, una tupla de enteros o una lista de enteros.

- `dtype` (opcional): Especifica el tipo de datos de los elementos del *array*. Por defecto, es `float`, lo que significa que los elementos del *array* serán números de punto flotante. También se pueden especificar otros tipos de datos, como `int` para números enteros, `bool` para valores booleanos, `str` para cadenas de texto, entre otros.



In [23]:
print("------------- ARRAY UNIDIMENSIONAL DE CEROS --------------")
# creamos el array unidimensional especificando el número de elementos que queremos tener en el array. 
# como solo tiene una dimensión solo le paso un valor.
array_vacio_unidimensional_cero =  np.zeros(4)
print(f"El array unidimensional creado a partir del método np.zeros(): \n  {array_vacio_unidimensional_cero} \n")

------------- ARRAY UNIDIMENSIONAL DE CEROS --------------
El array unidimensional creado a partir del método np.zeros(): 
  [0. 0. 0. 0.] 



In [24]:
print("------------- ARRAY BIDIMENSIONAL DE CEROS --------------")
# la lógica y la sintaxis va a ser la misma que cuando creabamos los arrays vacíos
# creamos un array de 0 con 4 filas y 2 columnas
array_vacio_bidimensional_cero =  np.zeros((4,2))
print(f"El array bidimensional creado a partir del método np.zeros(): \n  {array_vacio_bidimensional_cero} \n")

------------- ARRAY BIDIMENSIONAL DE CEROS --------------
El array bidimensional creado a partir del método np.zeros(): 
  [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 



In [25]:

print("------------- ARRAY TRIDIMENSIONAL DE CEROS --------------")
# estamos generando un array de 0 con 3 matrices donde cada una de ellas tienen 4 filas y 2 columnas
array_vacio_tridimensional_cero =  np.zeros((3, 4, 2)) 
print(f"El array tridimensional creado a partir del método np.zeros(): \n  {array_vacio_tridimensional_cero} \n")

------------- ARRAY TRIDIMENSIONAL DE CEROS --------------
El array tridimensional creado a partir del método np.zeros(): 
  [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]] 




## Crear un array de unos

Crea un *array* formado unicamente por 1. La sintaxis del método `np.ones` en NumPy es la siguiente:

```python
np.ones(shape, dtype=None)
```

- `shape`: Especifica la forma (dimensiones) del array que se creará. Puede ser un entero, una tupla de enteros o una lista de enteros. 


- `dtype` (opcional): Especifica el tipo de datos de los elementos del array. Por defecto, es `None`, lo que significa que los elementos del array serán números de punto flotante. También se pueden especificar otros tipos de datos, como `int` para números enteros, `bool` para valores booleanos, `str` para cadenas de texto, entre otros.

In [26]:
print("------------- ARRAY UNIDIMENSIONAL DE UNOS --------------")
# creamos el array de 1 unidimensional especificando el número de elementos que queremos tener en el array. 
# como solo tiene una dimensión solo le paso un valor.
array_vacio_unidimensional_unos =  np.ones(4)
print(f"El array unidimensional creado a partir del método np.ones(): \n  {array_vacio_unidimensional_unos} \n")

------------- ARRAY UNIDIMENSIONAL DE UNOS --------------
El array unidimensional creado a partir del método np.ones(): 
  [1. 1. 1. 1.] 



In [27]:
print("------------- ARRAY BIDIMENSIONAL DE UNOS --------------")
# estamos creando un array de dos dimensiones con 4 filas y 2 columnas
array_vacio_bidimensional_unos =  np.ones((4,2))
print(f"El array bidimensional creado a partir del método np.ones(): \n  {array_vacio_bidimensional_unos} \n")

------------- ARRAY BIDIMENSIONAL DE UNOS --------------
El array bidimensional creado a partir del método np.ones(): 
  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



In [28]:
print("------------- ARRAY TRIDIMENSIONAL DE UNOS --------------")
# creamos el array de 1 tridimensional especificando el número de elementos que queremos tener en el array. 
array_vacio_tridimensional_unos =  np.ones((3, 4, 2)) # estamos generando un array de tres matrices donde cada una de ellas tienen 4 filas y 2 columnas
print(f"El array tridimensional creado a partir del método np.ones(): \n  {array_vacio_tridimensional_unos} \n")

------------- ARRAY TRIDIMENSIONAL DE UNOS --------------
El array tridimensional creado a partir del método np.ones(): 
  [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]] 



## Crear un array con valores secuenciales


Funciona de forma similar al `range()` de Python, pero en este caso nos genera un *array*. La sintaxis del método `np.arange` en NumPy es la siguiente:

```python
np.arange(start, stop, step, dtype=None)
```

- `start` (opcional): Especifica el valor de inicio de la secuencia. Por defecto, es 0.

- `stop`: Especifica el valor final de la secuencia (exclusivo). Es decir, la secuencia generada no incluirá este valor.

- `step` (opcional): Especifica el incremento entre los valores de la secuencia. Por defecto, es 1.

- `dtype` (opcional): Especifica el tipo de datos de los elementos en el array. Por defecto, es `None`, lo que significa que se utilizará el tipo de datos predeterminado.


📌 Por defecto nos devuelve una matriz unidimensional. En caso de que queramos cambiar las dimensiones del *array* tendremos que aplicar el método `reshape` que veremos mas adelante. 

In [29]:
print("------------- ARRAY UNIDIMENSIONAL CON 4 ELEMENTOS --------------")
array_unidimensional_arange_1 =  np.arange(4)
print(f"El array unidimensional creado a partir del método np.emtpy(): \n  {array_unidimensional_arange_1} \n")


print("------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 4(no incluido) CON SALTOS DE 1 EN 1  --------------")
array_unidimensional_arange_2 =  np.arange(1,4,1)
print(f"El array bidimensional creado a partir del método np.emtpy(): \n  {array_unidimensional_arange_2} \n")


print("------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 20(no incluido) CON SALTOS DE 2 EN 2  --------------")
array_unidimensional_arange_3 =  np.arange(1,20,2)
print(f"El array bidimensional creado a partir del método np.emtpy(): \n  {array_unidimensional_arange_3} \n")


------------- ARRAY UNIDIMENSIONAL CON 4 ELEMENTOS --------------
El array unidimensional creado a partir del método np.emtpy(): 
  [0 1 2 3] 

------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 4(no incluido) CON SALTOS DE 1 EN 1  --------------
El array bidimensional creado a partir del método np.emtpy(): 
  [1 2 3] 

------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 20(no incluido) CON SALTOS DE 2 EN 2  --------------
El array bidimensional creado a partir del método np.emtpy(): 
  [ 1  3  5  7  9 11 13 15 17 19] 



## Crear un array usando random

El módulo `random` de NumPy proporciona funciones para generar números aleatorios con diferentes distribuciones y características. Estas funciones son útiles para simular datos aleatorios y realizar experimentos numéricos. Algunos de los métodos más utilizados del módulo `random` de NumPy:


1. `np.random.randint`: Genera números enteros aleatorios en un array. Puedes especificar el rango de los números enteros y la forma del array como argumentos.

2. `np.random.rand`: Genera números aleatorios en un *array* en el rango [0, 1).  Es decir, los números generados estarán en el intervalo semiabierto [0, 1), donde 0 está incluido y 1 está excluido.

3. `np.random.sample`: Genera números aleatorios en un *array*  en el rango [0, 1).


### np.random.randint

La sintaxis básica del método `np.random.randint` es la siguiente:

```python
numpy.random.randint(low, high, size, dtype)
```

Donde:

- `low`: Especifica el límite inferior del rango de números enteros a generar (inclusive). Si solo se proporciona este argumento, los números aleatorios se generarán en el rango [0, low). Es decir, el límite superior no está incluido en el rango.

- `high` (opcional): Especifica el límite superior del rango de números enteros a generar (exclusivo). Si se proporciona este argumento, los números aleatorios se generarán en el rango [low, high). 

- `size` (opcional): Especifica la forma del *array* resultante de números enteros aleatorios. Puede ser un número entero o una tupla de enteros que represente las dimensiones del *array*. Por defecto, es `None`, lo que implica que se generará un solo número entero,  es decir, un array unidimensional.

- `dtype` (opcional): Especifica el tipo de dato de los elementos en el *array*. Por defecto, es `int`, lo que significa que los números enteros se generarán como enteros estándar.



In [30]:
print("------------- ARRAY UNIDIMENSIONAL RANDINT --------------")
# en este caso estamos generando un array unidimensional con un valor aleatorio que puede variar entre 0 y 9 (no incluido)
array_randint_uni = np.random.randint(9)
print(f"El array unidimensional creado a partir del método np.random.randint(): \n  {array_randint_uni} \n")

------------- ARRAY UNIDIMENSIONAL RANDINT --------------
El array unidimensional creado a partir del método np.random.randint(): 
  3 



In [31]:
print("------------- ARRAY BIDIMENSIONAL RANDINT --------------")
# generamos un array bidimensional con números aleatorios entre el 0 y el 50(no incluido) de 2 filas y 3 columnas
array_randint_bi = np.random.randint(0, 50, (2,3))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_bi} \n")

------------- ARRAY BIDIMENSIONAL RANDINT --------------
El array bidimensional creado a partir del método np.random.randint(): 
  [[41 43  0]
 [25 13 14]] 



In [32]:
print("------------- ARRAY TRIDIMENSIONAL RANDINT --------------")
# generamos un array tridimensional de números aleatorios entre el 0 y 20 (no incluido) de 2 matrices, 3 filas y 4 columnas
array_randint_tri = np.random.randint(0, 20, (2,3, 4))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_tri} \n")

------------- ARRAY TRIDIMENSIONAL RANDINT --------------
El array bidimensional creado a partir del método np.random.randint(): 
  [[[14  1  6 18]
  [ 9  2 14  8]
  [ 8 12 15  7]]

 [[15 18  9  3]
  [11  7  9 17]
  [ 2  6 17  5]]] 



### np.random.rand

La sintaxis básica del método `np.random.rand` es la siguiente:

```python
numpy.random.rand(d0, d1, ..., dn)
```

- `d0, d1, ..., dn` son los argumentos opcionales que determinan las dimensiones de la matriz de números aleatorios que se generará. Puedes proporcionar cualquier número de argumentos, lo que significa que puedes crear matrices unidimensionales, bidimensionales, tridimensionales, etc.

📝 **NOTA**: en este caso no tenemos que especificar que entre que valores queremos que nos genere los números. POR DEFECTO NOS GENERARÁ NÚMEROS ALEATORIOS ENTRE EL 0-1.

📝 **NOTA**: Solo nos dará *floats*, por lo que no hace falta especificar el tipo. 

In [33]:
print("------------- ARRAY UNIDIMENSIONAL RAND --------------")
# en este caso estamos generando un array unidimensional con dos valores aleatorios entre el 0 y el 1
array_rand_uni = np.random.rand(2)
print(f"El array unidimensional creado a partir del método np.random.rand(): \n  {array_rand_uni} \n")

------------- ARRAY UNIDIMENSIONAL RAND --------------
El array unidimensional creado a partir del método np.random.rand(): 
  [0.71392317 0.51289174] 



In [34]:
print("------------- ARRAY BIDIMENSIONAL RAND --------------")
# en este caso estamos generando un array bidimensional de 2 filas y 3 columnas con números aleatorios entre el 0 y el 1
array_rand_bi = np.random.rand(2,3)
print(f"El array unidimensional creado a paratir del método np.random.rand(): \n  {array_rand_bi} \n")


------------- ARRAY BIDIMENSIONAL RAND --------------
El array unidimensional creado a paratir del método np.random.rand(): 
  [[0.97236031 0.56156805 0.49927621]
 [0.35977424 0.72944646 0.97662776]] 



In [35]:
print("------------- ARRAY TRIDIMENSIONAL RAND --------------")
# en este caso estamos generando un array tridimensional de 2 matrices, 3 filas  y 4 columnas con números aleatorios entre el 0 y el 1
array_rand_tri = np.random.rand(2,3, 4)
print(f"El array unidimensional creado a partir del método np.random.rand(): \n  {array_rand_tri} \n")


------------- ARRAY TRIDIMENSIONAL RAND --------------
El array unidimensional creado a partir del método np.random.rand(): 
  [[[0.85033862 0.13396745 0.77215805 0.59964628]
  [0.57378488 0.68387023 0.46357349 0.64262135]
  [0.33091832 0.62071512 0.06818836 0.79286998]]

 [[0.13307103 0.04586217 0.22683555 0.64552824]
  [0.88642237 0.73935487 0.76533122 0.94233981]
  [0.98199145 0.6614297  0.41842357 0.88499048]]] 



### np.random.random_sample

La sintaxis básica del método `np.random.random_sample` es la siguiente:

```python
numpy.random.random_sample(size=None)
```

Donde:

- `size` (opcional): Permite especificar la forma del array resultante. Puede ser un número entero o una tupla de enteros que represente las dimensiones del array. Si no se proporciona el parámetro `size`, se devuelve un solo número aleatorio en el rango [0, 1).

In [36]:
print("------------- ARRAY UNIDIMENSIONAL RANDOM_SAMPLE --------------")
# en este caso estamos generando un array unidimensional con 4 valores aleatorios entre el 0 y el 1
array_sample_uni = np.random.random_sample(4)
print(f"El array unidimensional creado a partir del método np.random.random_sample(): \n  {array_sample_uni} \n")

------------- ARRAY UNIDIMENSIONAL RANDOM_SAMPLE --------------
El array unidimensional creado a partir del método np.random.random_sample(): 
  [0.42557789 0.95662574 0.49035684 0.47086944] 



In [37]:
print("------------- ARRAY BIDIMENSIONAL RANDOM_SAMPLE --------------")
# en este caso estamos generando un array bidimensional de 2 filas y 3 columnas con números aleatorios entre el 0 y el 1
array_sample_bi = np.random.random_sample((2,3))
print(f"El array unidimensional creado a paratir del método np.random.random_sample(): \n  {array_sample_bi} \n")

------------- ARRAY BIDIMENSIONAL RANDOM_SAMPLE --------------
El array unidimensional creado a paratir del método np.random.random_sample(): 
  [[0.47228396 0.22426035 0.19634407]
 [0.59688199 0.64353557 0.33219936]] 



In [38]:
print("------------- ARRAY TRIDIMENSIONAL RANDOM_SAMPLE --------------")
# en este caso estamos generando un array tridimensional de 2 matrices, 3 filas  y 4 columnas con números aleatorios entre el 0 y el 1
array_sample_tri = np.random.random_sample((2,3, 4))
print(f"El array unidimensional creado a partir del método  np.random.random_sample(): \n  {array_sample_tri} \n")


------------- ARRAY TRIDIMENSIONAL RANDOM_SAMPLE --------------
El array unidimensional creado a partir del método  np.random.random_sample(): 
  [[[0.88156698 0.02038748 0.84520982 0.39661396]
  [0.41855205 0.84924726 0.36162263 0.31564645]
  [0.23977595 0.75099621 0.27634375 0.70419236]]

 [[0.83138214 0.93820041 0.07428851 0.66786977]
  [0.69558011 0.05753442 0.25096624 0.73236191]
  [0.4018233  0.44677918 0.89489079 0.07356772]]] 



# Indexación 

Se utiliza para acceder a elementos especificando sus índices dentro del *array*, de una forma muy similar a como lo hacíamos con listas.

Si recordamos de las listas: 

- Empezabamos a contar las posiciones de nuestros elementos desde 0. **En NumPy será igual**.

    ![image.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/index_Numpy.png?raw=true)


- Si queremos acceder a un subconjunto de elementos de nuestra lista usabamos la siguiente sintaxis:

    ```python
    lista[start:stop:step]

    # ejemplo:
    lst = [12,20,3,45,6,23,81,93]

    # seleccionamos desde el elemento 3 (incluido) hasta el final
    lst[3:] 
    [45, 6, 23, 81, 93]


    # seleccionamos desde el elemento 3 hasta el 5. ⚠️ Recordamos que en el límite superior el valor que especificamos NO SE INCLUYE
    lst[3:6]
    [45, 6, 23]


    # seleccionamos los 4 primeros elementos
    lst[:4]
    [12, 20, 3, 45]


    # seleccionamos todos los elementos que están en posición impar
    lst[1::2]
    [12, 3, 6, 81]
    ```

## Indexación en *arrays* unidimensionales

Como ya hemos dicho, la indexación se utiliza para acceder y manipular elementos individuales o grupos de elementos en un array. En NumPy, la indexación se realiza utilizando corchetes `[]`, al igual que hacíamos en listas. 

```python
array[i]
# donde i es el índice del elemento al que queremos acceder
```


In [39]:
# Imaginemos que tenemos el siguiente array unidimensional con 5 elementos
## en nuestro array

unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos acceder al primer elemento de nuestro array
print("\n---------------------------\n")
print(f"El primer elemento de nuestro array es: \n {unidimensional[0]}")

El array unidimensional que tenemos es: 
 [0.32573466 0.84880049 0.57053103 0.88727353 0.96049254 0.49598935
 0.64505759 0.68222103 0.08355165 0.76326667 0.24582577 0.51407219
 0.32139353 0.61957795 0.42491048]

---------------------------

El primer elemento de nuestro array es: 
 0.3257346573405563


In [40]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")


# si queremos acceder a los tres últimos elementos:
print("\n---------------------------\n")
print(f"Los tres últimos elementos de nuestro array son: \n {unidimensional[-3:]}")

El array unidimensional que tenemos es: 
 [0.62795091 0.27185442 0.35112754 0.22196279 0.41286824 0.11944249
 0.57844201 0.20832481 0.65744568 0.03546854 0.76620912 0.42861934
 0.78726559 0.17907503 0.36370131]

---------------------------

Los tres últimos elementos de nuestro array son: 
 [0.78726559 0.17907503 0.36370131]


In [41]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos seleccionar el tercer y cuarto elemento
print("\n---------------------------\n")
print(f"El tercer y cuarto elemento de nuestro array son: \n {unidimensional[2:4]}")


El array unidimensional que tenemos es: 
 [0.6479038  0.4108167  0.60073703 0.74096401 0.19396467 0.4276144
 0.82327239 0.65265762 0.01331434 0.05560851 0.51149955 0.63357237
 0.44233538 0.04228726 0.2470867 ]

---------------------------

El tercer y cuarto elemento de nuestro array son: 
 [0.60073703 0.74096401]


In [42]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# los elementos desde el inicio hasta el 10 en saltos de dos en dos
print("\n---------------------------\n")
print(f"Los elementos desde el inicio hasta el 10 de dos en dos son: \n {unidimensional[:11:2]}")



El array unidimensional que tenemos es: 
 [0.68228048 0.69717168 0.93672724 0.74361115 0.33452501 0.5084577
 0.92410222 0.86370289 0.18249394 0.0770544  0.94879844 0.84181276
 0.71305865 0.42357907 0.54693518]

---------------------------

Los elementos desde el inicio hasta el 10 de dos en dos son: 
 [0.68228048 0.93672724 0.33452501 0.92410222 0.18249394 0.94879844]


## Indexación en *arrays* bidimensionales

En el caso de este tipo de *arrays* se acceder a elementos individuales en una matriz bidimensional utilizando la sintaxis `[fila, columna]` entre corchetes.

Los podemos entender como una lista de listas.

```python
array[i,j]
array[i][j]

# 🚨 Las dos lineas anteriores son exactamente lo mismo
# seleccionará el elemento de la fila "i" y columna "j"
```


Donde: 
- `i` --> filas

- `j` --> columnas

In [43]:
# definimos un array bidimensional
# en este caso estamos generando un array de 5 filas y 4 columnas con números aleatorios entre el 0 y el 1
bidimensional = np.random.rand(5, 4)
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# desgranemos la indexación en este tipo de arrays
# si accedemos al elemento 0 del array obtenemos a la fila que queramos de nuestro array

print(f"\nEl primer elemento de nuestro array es: \n {bidimensional[0]}")

El array bidimensional que tenemos es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]

El primer elemento de nuestro array es: 
 [0.44651686 0.78119643 0.88881996 0.26448012]


In [44]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# dado el resultado del paso anterior, sigamos buceando en el array, 
# en este caso querremos acceder al primer elemento del resultado anterior
# fijaos como ponemos dos indices, el primero para acceder a las filas 
# y el segundo para acceder a las columnas
# podríamos decir que es como el juego de hundir la flota
print(f"\nEl primer elemento de la primera fila de nuestro array es: \n {bidimensional[0][0]}")
print("\n-------------------------------------\n")
print(f"bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: \n {bidimensional[0, 0]}")

El array bidimensional que tenemos es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]

El primer elemento de la primera fila de nuestro array es: 
 0.44651685551490206

-------------------------------------

bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: 
 0.44651685551490206


In [45]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")
# accedemos a la segunda fila, tercer columna. 
print("\n---------------------------\n")
print(f"El elemento que esta en la 2ª fila y 3ª columna es: \n {bidimensional[1,2]}")


El array bidimensional que tenemos es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]

---------------------------

El elemento que esta en la 2ª fila y 3ª columna es: 
 0.6481959486879245


📌 **NOTA** Cuando usamos la siguiente estructura `array[i,j]`: 

- Todo lo que haya antes de la coma se referirá a filas.


- Todo lo que haya después de la coma se referirá a columnas. 

De esta forma, si por ejemplo queremos seleccionar solo las dos primeras filas usaremos la nomenclatura que ya conocemos con los `:`. Si no especificamos nada (o solo ponemos `:`) se entiende que lo queremos todo. Por ejemplo 👇🏽

In [46]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")
# seleccionamos las dos primeras filas, y todas las columnas (no ponemos 
# nada después de la coma). 
print("\n---------------------------\n")
print(f"Las dos primeras filas con todas sus columnas son: \n {bidimensional[:2,:]}")



El array bidimensional que tenemos es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]

---------------------------

Las dos primeras filas con todas sus columnas son: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]]


In [47]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# seleccionamos todas las filas y solo las tres últimas filas
print("\n---------------------------\n")
print(f"Todas las filas y las últimas tres columnas son: \n {bidimensional[:,-3:]}")

El array bidimensional que tenemos es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]

---------------------------

Todas las filas y las últimas tres columnas son: 
 [[0.78119643 0.88881996 0.26448012]
 [0.17579086 0.64819595 0.58163478]
 [0.27941749 0.98465093 0.07181733]
 [0.39021528 0.78628449 0.53765086]
 [0.52555423 0.4473433  0.63404601]]


## Indexación en *arrays* tridimensionales

De la misma forma que en los bidimensionales, el los mutidimensionales podemos acceder a sus elementos de dos formas: 

```python
array[i,j,k]
array[i][j][k]
```

- i → *array* al que queremos acceder 


- j → fila de nuestro *array* al que queremos acceder


- k → columna de nuestro *array* al que queremos acceder

    ![3d-array-index.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/index_numpy_multidimensional.png?raw=true)

In [48]:
# definimos un array tridimensional
# en este caso estamos creando un array de números enteros entre el 10 y el 100 con
# 2 matrices, 3 filas y 5 columnas
tridimensional = np.random.randint(10,100, (2,3,5))
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# accedemos al primer array y al elemento que está en la fila 2 y la columna 4
print("\n---------------------------\n")
print(f"El elemento de la 1ª matriz, 2ª fila y 4ª columna es : \n {tridimensional[0,1,3]}")

El array multidimensional que tenemos es: 
 [[[39 62 83 33 74]
  [77 25 12 75 60]
  [30 13 73 14 72]]

 [[45 22 74 76 42]
  [20 34 75 30 14]
  [68 27 72 77 34]]]

---------------------------

El elemento de la 1ª matriz, 2ª fila y 4ª columna es : 
 75


In [49]:
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# primer array primera fila y todas las columnas
print("\n---------------------------\n")
print(f"Los elementos del 1ª matriz, 1ª fila y todas las columnas  : \n {tridimensional[0,0, :]}")


El array multidimensional que tenemos es: 
 [[[39 62 83 33 74]
  [77 25 12 75 60]
  [30 13 73 14 72]]

 [[45 22 74 76 42]
  [20 34 75 30 14]
  [68 27 72 77 34]]]

---------------------------

Los elementos del 1ª matriz, 1ª fila y todas las columnas  : 
 [39 62 83 33 74]


# Filtrado de datos en *arrays*

## Filtrado con condiciones

El filtrado de datos en *arrays* de NumPy es una técnica para seleccionar elementos específicos de un *array* basado en ciertas condiciones. NumPy proporciona una forma eficiente de filtrar datos utilizando operaciones booleanas.

Los pasos para poder filtrar datos en *arrays* de NumPy son:

1. **Creación de una máscara booleana**: En el filtrado de datos, primero necesitamos crear una máscara booleana, que es un *array* booleano que tiene la misma forma que el *array* original. La máscara booleana contiene valores True o False, donde True indica que un elemento cumple una determinada condición y False indica que no la cumple. Por ejemplo:
    ```python

    array = np.array([1, 2, 3, 4, 5])
    mascara = array > 3  # Crear una máscara booleana donde los elementos mayores que 3 son True
    ```

2. **Aplicación de la máscara booleana**: Una vez que tenemos la máscara booleana, podemos aplicarla para filtrar los datos del *array* original. Puedes utilizar la máscara booleana como índice para seleccionar los elementos correspondientes del array original. Por ejemplo:
    ```python
    elementos_filtrados = array[mascara]  # Filtrar los elementos del array original usando la máscara booleana
    ```

In [50]:
# en este caso reutilizaremos el array bidimensional que creamos en el apartado anterior
print(f"El array bidimensional con el que vamos a trabajar es: \n {bidimensional}")

# creamos la máscara, en este caso nuestra condición será: ¿qué elementos son mayores que 0.5?
print("-----------------------------")
print(f"Primer paso: creación de una máscara booleana \n {bidimensional > 0.5}")

# aplicamos la máscara creada en el paso anterior, en este caso, NumPy nos devolverá solo los elementos 
# que coinciden con la condicion
print("-----------------------------")
print(f"Segundo paso: aplicar la máscara booleana \n {bidimensional[bidimensional > 0.5]}")

El array bidimensional con el que vamos a trabajar es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]
-----------------------------
Primer paso: creación de una máscara booleana 
 [[False  True  True False]
 [ True False  True  True]
 [ True False  True False]
 [False False  True  True]
 [False  True False  True]]
-----------------------------
Segundo paso: aplicar la máscara booleana 
 [0.78119643 0.88881996 0.83547254 0.64819595 0.58163478 0.7594619
 0.98465093 0.78628449 0.53765086 0.52555423 0.63404601]


Imaginemos ahora que queremos seleccionar ciertos valores basados en dos condiciones. En este caso:

- Usaremos el operador `&` para indicar que queremos que se cumplan las dos condiciones. Lo que conocíamos hasta ahora como `and`.


- Usaremos el operador `|` para indicar que se cumpla una condición y otra. Lo que conocíamos hasta ahora como `or`. 

In [51]:
# en este caso reutilizaremos el array bidimensional que creamos en el apartado anterior
print(f"El array bidimensional con el que vamos a trabajar es: \n {bidimensional}")


# queremos seleccionar aquellos números que sean MENORES que 0.2 
# o MAYORES que 0.7. FIJATE QUE CADA CONDICIÓN VA ENTRE PARÉNTESIS SEPARADA POR EL OPERADOR "|"
print("-----------------------------")
resultado_filtradoI = bidimensional[(bidimensional < 0.2) |  (bidimensional >0.7)]
print(f"El resultado del filtraod < 0.2 o > 0.7 es: \n {resultado_filtradoI}")

El array bidimensional con el que vamos a trabajar es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]
-----------------------------
El resultado del filtraod < 0.2 o > 0.7 es: 
 [0.78119643 0.88881996 0.83547254 0.17579086 0.7594619  0.98465093
 0.07181733 0.78628449 0.18720335]


## Filtrado con `np.where()`

Permite realizar una evaluación condicional sobre un *array*. La función `np.where()` devuelve un nuevo array con los elementos seleccionados según la condición especificada.

Su sintaxis básica es:
```python
np.where(condición, valor_si_verdadero, valor_si_falso)
```

Donde:

- **condición**: Es una expresión booleana que define la condición a evaluar. 

- **valor_si_verdadero** (opcional):  Es el valor o array que se selecciona si la condición es verdadera.

- **valor_si_falso** (opcional): Es el valor o array que se selecciona si la condición es falsa.

In [52]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional}")

# usamos el método 'np.where()' para evaluar una condición, en este caso para encontrar los valores mayores que 0.8
resultado_where = np.where(bidimensional > 0.8)
print("--------------------------")
print("El resultado del np.where() es: \n", resultado_where)



El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.44651686 0.78119643 0.88881996 0.26448012]
 [0.83547254 0.17579086 0.64819595 0.58163478]
 [0.7594619  0.27941749 0.98465093 0.07181733]
 [0.39710703 0.39021528 0.78628449 0.53765086]
 [0.18720335 0.52555423 0.4473433  0.63404601]]
--------------------------
El resultado del np.where() es: 
 (array([0, 1, 2]), array([2, 0, 2]))


Interpretemos el *output* que nos da: 
 📌 ¡Ojo! Estos datos pueden variar en función del array! Pero analicemos este posible resultado y luego extrapolemoslo a tus resultados:
 
Siendo el *array* 

```python
# siendo el array: 
 [[0.77903991 0.15437117 0.57456639 0.7733642 ]
 [0.57071481 0.85731511 0.45343035 0.88811929]
 [0.59041327 0.54515411 0.1909847  0.64404005]
 [0.39462897 0.93674338 0.89013927 0.38247099]
 [0.90641556 0.00374108 0.44098083 0.19549975]]

# y estableciendo la siguiente condición: 
np.where(bidimensional > 0.9)

# lo primero que vemos es que nos devuelve una tupla, que tiene dos arrays
(array([3, 4]), array([1, 0]))
```

- El primer *array* del *output* hace referencia a las filas

    ```python
    array([3, 4])
    ```

- El segundo *array* hace refencia a las columnas

    ```python
    array([1, 0])
    ```

Entonces ¿qué significa?

- El elemento `3,1` (fila, columna) cumple la condición.
- El elemento `4,0` (fila, columna) cumple la condición.

🚨 **NOTA** Fijaos que los valores de estos índices pueden variar cada vez que ejecutemos el código ya que estamos generando el *array* de forma aleatoria. 

# Operaciones aritméticas con *arrays* 

*NumPy* proporciona una amplia gama de funciones y operaciones para realizar cálculos aritméticos en *arrays* de manera eficiente.

Algunas de las operaciones aritméticas comunes que puedes realizar con arrays de NumPy:

1. Suma: Usaremos el método `np.add()`
  
2. Resta: En este caso`np.subtract()`

3. Multiplicación: Usaremos `np.multiply()`

4. División: Método `np.divide()`

5. Potencia: Usaremos el método `np.power()`

6. Operaciones con escalares

Los operadores `+`, `-`, `*` y `/` también funcionan para realizar las operaciones correspondientes directamente entre *arrays* de *NumPy*. Sin embargo, aunque los podemos usar, los métodos aprendidos específicos de NumPy son los más adecuados.

In [53]:
# lo primero que vamos a hacer es definir dos arrays con los que trabajaremos. 
# en este caso vamos a generar dos arrays tridimensionales con números enteros entre el 1 y 10
# lel array consta de 2 matrices, 2 filas y tres colummas 
array1 = np.random.randint(1,10, (2, 2,3))
array2 = np.random.randint(1,10, (2, 2,3))

print("El array 1 es:\n ", array1, '\n')
print("El array 2 es:\n ", array2)

# sumar dos arrays
print("--------------------------------")
suma = np.add(array1, array2)  # Suma los elementos correspondientes de los dos arrays
print("El resultado de la suma de los dos arrays es:\n", suma)


El array 1 es:
  [[[4 9 4]
  [8 4 4]]

 [[9 9 5]
  [4 4 7]]] 

El array 2 es:
  [[[8 8 8]
  [2 6 1]]

 [[1 2 5]
  [7 6 3]]]
--------------------------------
El resultado de la suma de los dos arrays es:
 [[[12 17 12]
  [10 10  5]]

 [[10 11 10]
  [11 10 10]]]


In [54]:

print("El array 1 es:\n ", array1, '\n')
print("El array 2 es:\n ", array2)

# restar dos arrays
print("--------------------------------")
resta = np.subtract(array1, array2)  # Suma los elementos correspondientes de los dos arrays
print("El resultado de la resta de los dos arrays es:\n", resta)

El array 1 es:
  [[[4 9 4]
  [8 4 4]]

 [[9 9 5]
  [4 4 7]]] 

El array 2 es:
  [[[8 8 8]
  [2 6 1]]

 [[1 2 5]
  [7 6 3]]]
--------------------------------
El resultado de la resta de los dos arrays es:
 [[[-4  1 -4]
  [ 6 -2  3]]

 [[ 8  7  0]
  [-3 -2  4]]]


In [55]:
print("El array 1 es:\n ", array1, '\n')
print("El array 2 es:\n ", array2)

# multiplicar dos arrays
print("--------------------------------")
multipicacion = np.multiply(array1, array2)  # Suma los elementos correspondientes de los dos arrays
print("El resultado de la multiplicación de los dos arrays es:\n", multipicacion)



El array 1 es:
  [[[4 9 4]
  [8 4 4]]

 [[9 9 5]
  [4 4 7]]] 

El array 2 es:
  [[[8 8 8]
  [2 6 1]]

 [[1 2 5]
  [7 6 3]]]
--------------------------------
El resultado de la multiplicación de los dos arrays es:
 [[[32 72 32]
  [16 24  4]]

 [[ 9 18 25]
  [28 24 21]]]


In [56]:
print("El array 1 es:\n ", array1, '\n')
print("El array 2 es:\n ", array2)

# dividir dos arrays
print("--------------------------------")
division = np.divide(array1, array2)  # Suma los elementos correspondientes de los dos arrays
print("El resultado de la división de los dos arrays es:\n", division)

El array 1 es:
  [[[4 9 4]
  [8 4 4]]

 [[9 9 5]
  [4 4 7]]] 

El array 2 es:
  [[[8 8 8]
  [2 6 1]]

 [[1 2 5]
  [7 6 3]]]
--------------------------------
El resultado de la división de los dos arrays es:
 [[[0.5        1.125      0.5       ]
  [4.         0.66666667 4.        ]]

 [[9.         4.5        1.        ]
  [0.57142857 0.66666667 2.33333333]]]


In [57]:
print("El array 1 es:\n ", array1, '\n')
print("El array 2 es:\n ", array2)

# elevar dos arrays
print("--------------------------------")
elevado = np.power(array1, array2)  # Suma los elementos correspondientes de los dos arrays
print("El resultado de la potencia de los dos arrays es:\n", elevado)

El array 1 es:
  [[[4 9 4]
  [8 4 4]]

 [[9 9 5]
  [4 4 7]]] 

El array 2 es:
  [[[8 8 8]
  [2 6 1]]

 [[1 2 5]
  [7 6 3]]]
--------------------------------
El resultado de la potencia de los dos arrays es:
 [[[   65536 43046721    65536]
  [      64     4096        4]]

 [[       9       81     3125]
  [   16384     4096      343]]]


In [58]:
print("El array 1 es:\n ", array1, '\n')

# operaciones con escalares
# definimos un escalar
print("--------------------------------")
escalar = 2
multiplicacion_escalar = array1 * escalar
print("El resultado de la multiplicación del array con el escalar es:\n", multiplicacion_escalar)

El array 1 es:
  [[[4 9 4]
  [8 4 4]]

 [[9 9 5]
  [4 4 7]]] 

--------------------------------
El resultado de la multiplicación del array con el escalar es:
 [[[ 8 18  8]
  [16  8  8]]

 [[18 18 10]
  [ 8  8 14]]]


# Funciones universales o `ufuncs`

Las Funciones Universales (*ufuncs*) de NumPy permiten realizar operaciones eficientes elemento por elemento en *arrays* de NumPy. Estas funciones proporcionan un rendimiento optimizado, una amplia variedad de operaciones. 

## Operaciones estadísticas

### `np.mean()`

Calcula la media de todos los elementos del *array*. La **media** es una medida estadística que se utiliza para obtener el valor central de un conjunto de datos numéricos. Para calcular la media, se suman todos los valores y se dividen por la cantidad total de valores.

Este método nos permite elegir el eje sobre el que queremos calcular la media. Para eso tendremos que usar el parámetro `axis`, donde:

- `axis = 0`: nos calculará la media para cada **columna** de nuestro *array*.

    ![mean.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/mean_numpy.png?raw=true)

- `axis = 1`: nos calculará la media para cada **fila** de nuestro *array*.

    ![mean_filas.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/mean_numpy_filas.png?raw=true)


Cuando pasamos este parámetro la función `np.mean` produce un nuevo *array* con los resultados. 

In [59]:
# antes de seguir vamos a aprender el método np.round(), que al igual que en Python básico nos permite redondear los valores de los elementos de nuestor array
bidimensional_red = np.round(bidimensional, 2)
bidimensional_red

array([[0.45, 0.78, 0.89, 0.26],
       [0.84, 0.18, 0.65, 0.58],
       [0.76, 0.28, 0.98, 0.07],
       [0.4 , 0.39, 0.79, 0.54],
       [0.19, 0.53, 0.45, 0.63]])

In [60]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la media de todos los elementos de array
media = np.mean(bidimensional_red)
print("--------------------------")
print(f"El cálculo de la media de todos los elementos del array es: \n {media}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El cálculo de la media de todos los elementos del array es: 
 0.5319999999999999


In [61]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la media por cada COLUMNA que tenemos en el array
media_col = np.mean(bidimensional_red, axis = 0)
print("--------------------------")
print(f"La media de cada COLUMNA (axis = 0) del array es: \n {media_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
La media de cada COLUMNA (axis = 0) del array es: 
 [0.528 0.432 0.752 0.416]


In [62]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos la media por cada FILA que tenemos en el array
media_fila = np.mean(bidimensional_red, axis = 1)
print("--------------------------")
print(f"La media de cada FILA (axis = 1) del array es: \n {media_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
La media de cada FILA (axis = 1) del array es: 
 [0.595  0.5625 0.5225 0.53   0.45  ]


### `np.var()`

Calcula la varianza de los valores de mi *array*. Por defecto lo hará sobre todo el *array*, pero nosotros le podemos especificar el eje usando el parámetro `axis`. La **varianza** es una medida estadística que indica qué tan dispersos están los valores de un conjunto de datos alrededor de su media. Es una medida de la variabilidad de los datos. Una varianza alta indica que los valores están más dispersos, mientras que una varianza baja indica que los valores están más cercanos a la media.

- `axis = 0`: columnas
- `axis = 1`: filas



In [63]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la varianza de todos los elementos de array
varianza = np.var(bidimensional_red)
print("--------------------------")
print(f"El cálculo de la varianza de todos los elementos del array es: \n {varianza}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El cálculo de la varianza de todos los elementos del array es: 
 0.06362599999999999


In [64]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos la varianza por cada COLUMNA que tenemos en el array
varianza_col = np.var(bidimensional_red, axis = 0)
print("--------------------------")
print(f"La varianza de cada COLUMNA (axis = 0) del array es: \n {varianza_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
La varianza de cada COLUMNA (axis = 0) del array es: 
 [0.057576 0.043816 0.034816 0.046424]


In [65]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos la varianza por cada FILA que tenemos en el array
varianza_fila = np.var(bidimensional_red, axis = 1)
print("--------------------------")
print(f"La varianza de cada FILA (axis = 1) del array es: \n {varianza_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
La varianza de cada FILA (axis = 1) del array es: 
 [0.063625   0.05781875 0.13231875 0.02605    0.0266    ]


### `np.std()`

Calcula la desviación estándar en nuestro *array*, como hasta ahora, por defecto nos lo va a calcular para todos los elementos. La **desviación estándar** es una medida estadística que indica cuánto varían los valores de un conjunto de datos con respecto a la media. Proporciona una medida de dispersión o variabilidad en los datos. Una desviación estándar alta indica que los valores del conjunto de datos están más dispersos, mientras que una desviación estándar baja indica que los valores están más cerca de la media.


Entonces... ¿Cuál es la diferencia entre desviación y varianza?

- La varianza mide la dispersión de los datos alrededor de la media, expresada en unidades al cuadrado.
- La desviación estándar mide la dispersión de los datos alrededor de la media, expresada en las mismas unidades que los datos originales.

Si le pasamos el parámetro `axis` podemos especificar sobre que eje queremos que nos calcule la desviación estándar. 

- `axis = 0`: columnas
- `axis = 1`: filas

In [66]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la desviación de todos los elementos de array
desviación = np.std(bidimensional_red)
print("--------------------------")
print(f"El cálculo de la desviacion de todos los elementos del array es: \n {desviación}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El cálculo de la desviacion de todos los elementos del array es: 
 0.2522419473442115


In [67]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos la desviación por cada COLUMNA que tenemos en el array
desviacion_col = np.std(bidimensional_red, axis = 0)
print("--------------------------")
print(f"La desviación de cada COLUMNA (axis = 0) del array es: \n {desviacion_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
La desviación de cada COLUMNA (axis = 0) del array es: 
 [0.23994999 0.20932272 0.18659046 0.21546229]


In [68]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos la desviación por cada FILA que tenemos en el array
desviacion_fila = np.std(bidimensional_red, axis = 1)
print("--------------------------")
print(f"La desviación de cada FILA (axis = 1) del array es: \n {desviacion_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
La desviación de cada FILA (axis = 1) del array es: 
 [0.25223997 0.2404553  0.36375644 0.16140012 0.16309506]


## Operaciones aritméticas

### `np.min()`

Nos devuelve el valor mínimo de nuestro *array*. 

De la misma forma que `np.mean()` nos va a permitir identificar los valores mínimos a través de las columnas o las filas usando el parámetro `axis`. 

Igual que en `np.mean()`:

- `axis = 0`: columnas
- `axis = 1`: filas

In [69]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# sacamos el valor mínimo del array
minimo = np.min(bidimensional_red)
print("--------------------------")
print(f"El valor mínimo de todos los elementos del array es: \n {minimo}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor mínimo de todos los elementos del array es: 
 0.07


In [70]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# sacamos el valor mínimo de cada COLUMNA que tenemos en el array
minimo_col = np.min(bidimensional_red, axis = 0)
print("--------------------------")
print(f"El valor mínimo de cada COLUMNA (axis = 0) del array es: \n {minimo_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor mínimo de cada COLUMNA (axis = 0) del array es: 
 [0.19 0.18 0.45 0.07]


In [71]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# sacamos el valor mínimo de cada FILA que tenemos en el array
minimo_fila = np.min(bidimensional_red, axis = 1)
print("--------------------------")
print(f"El valor mínimo de cada FILA (axis = 1) del array es: \n {minimo_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor mínimo de cada FILA (axis = 1) del array es: 
 [0.26 0.18 0.07 0.39 0.19]


### `np.max()`

Nos devuelve el valor máximo de nuestro *array*. 

Podemos seguir trabajando con el parámetro `axis` para sacar los valores máximos por filas o columnas:

- `axis = 0`: columnas
- `axis = 1`: filas

In [72]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos el valor máximo de todos los elementos del array
maximo = np.max(bidimensional_red)
print("--------------------------")
print(f"El valor máximo de todos los elementos del array es: \n {maximo}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor máximo de todos los elementos del array es: 
 0.98


In [73]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos el valor máximo por cada COLUMNA que tenemos en el array
maximo_col = np.max(bidimensional_red, axis = 0)
print("--------------------------")
print(f"El valor máximo de cada COLUMNA (axis = 0) del array es: \n {maximo_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor máximo de cada COLUMNA (axis = 0) del array es: 
 [0.84 0.78 0.98 0.63]


In [74]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos el valor máximo por cada FILA que tenemos en el array
maximo_fila = np.max(bidimensional_red, axis = 1)
print("--------------------------")
print(f"El valor máximo de cada FILA (axis = 1) del array es: \n {maximo_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor máximo de cada FILA (axis = 1) del array es: 
 [0.89 0.84 0.98 0.79 0.63]


### `np.sum()`

Suma los elementos del *array*. Por defecto nos va a sumar todos los elementos del *array* (nos devuelve un único valor). Podemos especificar que nos haga la suma por filas o columnas con el parámetro `axis` (nos devolverá un valor por cada fila o columna que tengamos):

- `axis = 0`: columnas
- `axis = 1`: filas

In [75]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la suma de todos los elementos de array
suma = np.sum(bidimensional_red)
print("--------------------------")
print(f"La suma de todos los elementos del array es: \n {suma}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
La suma de todos los elementos del array es: 
 10.639999999999999


In [76]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos la suma de todos los elementos por cada COLUMNA que tenemos en el array
suma_col = np.sum(bidimensional_red, axis = 0)
print("--------------------------")
print(f"El valor máximo de cada COLUMNA (axis = 0) del array es: \n {suma_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor máximo de cada COLUMNA (axis = 0) del array es: 
 [2.64 2.16 3.76 2.08]


In [77]:

print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")
# calculamos la suma de todos los elementos por cada FILA que tenemos en el array
suma_fila = np.sum(bidimensional_red, axis = 1)
print("--------------------------")
print(f"El valor máximo de cada FILA (axis = 1) del array es: \n {suma_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------
El valor máximo de cada FILA (axis = 1) del array es: 
 [2.38 2.25 2.09 2.12 1.8 ]


## Otros métodos

### `np.sort()`

Devuelve una copia ordenada de un *array*.

Por defecto nos ordenará por filas de nuestro *array*, si lo que queremos es que nos ordene por columnas tendremos que pasarle el parámetro `axis = 0`. 

In [78]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# ordenamos el array con el método np.sort()
bidimensional_red_ordenado_filas = np.sort(bidimensional_red)
print("--------------------------\n")
print("El array ordenado por CADA FILA de menor a mayor es: \n", bidimensional_red_ordenado_filas)


El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------

El array ordenado por CADA FILA de menor a mayor es: 
 [[0.26 0.45 0.78 0.89]
 [0.18 0.58 0.65 0.84]
 [0.07 0.28 0.76 0.98]
 [0.39 0.4  0.54 0.79]
 [0.19 0.45 0.53 0.63]]


Si nos fijamos, el *array* esta ordenado de menor a mayor en cada fila. Si quisieramos ordenarlo de menor a mayor por columnas tendremos que usar el parámetro `axis = 0`

In [79]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# ordenamos el array con el método np.sort()
bidimensional_red_ordenado_col = np.sort(bidimensional_red, axis = 0)
print("--------------------------\n")
print("El array ordenado por CADA COLUMNA de menor a mayor es: \n", bidimensional_red_ordenado_col)

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------

El array ordenado por CADA COLUMNA de menor a mayor es: 
 [[0.19 0.18 0.45 0.07]
 [0.4  0.28 0.65 0.26]
 [0.45 0.39 0.79 0.54]
 [0.76 0.53 0.89 0.58]
 [0.84 0.78 0.98 0.63]]


⚠️ Si nos fijamos en cualquiera de los casos nos esta ordenando de menor a mayor. 

Pero... ¿Qué pasaría si quisieramos ordenar de mayor a menor? 

Le tendríamos que dar la vuelta primero al *array* y luego ordenarlo. ¿Cómo podemos darle la vuelta a un *array*? 

> Utilizando el operador `-` delante del *array* y del método


In [80]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# le ponemos un símbolo '-' al array, fijaos que lo ponemos todos los elementos a negativos
print("--------------------------\n")
print(f"El array con un símbolo '-' antes es: \n {-bidimensional_red}")

# ahora vamos a ordenar este array con el método np.sort()
print("--------------------------\n")
print(f"El array con un símbolo '-' antes y usando el método 'np.sort()' es: \n {np.sort(-bidimensional_red)}")

# si nos fijamos ahora, si ignoramos los símbolos '-' los valores más altos están al inicio de las filas, por lo que
# tendremos que hacer ahora es quitarle los símbolos '-'. Para eso lo que haremos será poner un símbolo '-' delante del 'np.sort()'
print("--------------------------\n")
print(f"El array con un símbolo '-' antes y usando el método 'np.sort()' y volviendolo a poner en negativo es: \n {-np.sort(-bidimensional_red)}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------

El array con un símbolo '-' antes es: 
 [[-0.45 -0.78 -0.89 -0.26]
 [-0.84 -0.18 -0.65 -0.58]
 [-0.76 -0.28 -0.98 -0.07]
 [-0.4  -0.39 -0.79 -0.54]
 [-0.19 -0.53 -0.45 -0.63]]
--------------------------

El array con un símbolo '-' antes y usando el método 'np.sort()' es: 
 [[-0.89 -0.78 -0.45 -0.26]
 [-0.84 -0.65 -0.58 -0.18]
 [-0.98 -0.76 -0.28 -0.07]
 [-0.79 -0.54 -0.4  -0.39]
 [-0.63 -0.53 -0.45 -0.19]]
--------------------------

El array con un símbolo '-' antes y usando el método 'np.sort()' y volviendolo a poner en negativo es: 
 [[0.89 0.78 0.45 0.26]
 [0.84 0.65 0.58 0.18]
 [0.98 0.76 0.28 0.07]
 [0.79 0.54 0.4  0.39]
 [0.63 0.53 0.45 0.19]]


### `np.transpose()`

Es una función de la biblioteca NumPy que se utiliza para intercambiar las dimensiones de un *array*. Toma como argumento un *array* y devuelve una nueva *array* con las dimensiones intercambiadas.

La sintaxis básica de `np.transpose` es la siguiente:

```python
np.transpose(arr, axes)
```

Donde:
- `arr`: Es la matriz que deseas transponer.
- `axes`: Es una tupla opcional que especifica cómo se deben reordenar las dimensiones. Cada elemento de la tupla representa la dimensión correspondiente en la matriz transpuesta. Si no se proporciona `axes`, se realiza una permutación de las dimensiones en orden inverso.

Visualmente lo podemos ver así:


![image-2.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/transpose.png?raw=true)


En resumen, `np.transpose` es una función útil para cambiar las dimensiones de una matriz en NumPy. Puede ser especialmente útil en el análisis de datos cuando se necesita cambiar el orden de filas y columnas para realizar cálculos o manipulaciones específicas.


Veamos varios ejemplos con arrays de distintas dimensiones:

#### Unidimensional

No tiene mucho sentido hacer una transposición de un *array* de una dimensión ya que:

> La transposición de un *array* unidimensional devuelve una vista inalterada del *array* original.

#### Bidimensional

Va ha cambiar las filas por columnas en nuestro *array*

In [81]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# transponemos el array bidimensional usando el método'np.transpose()'
# Fijaos como después de aplicar el método transpose tenemos 4 filas y 5 columnas. El array original tenia 5 filas  y 4 columnas
print("--------------------------\n")
bidimensional_red_trans = np.transpose(bidimensional_red)
print(f"El array después de aplicar el método 'np.transpose()': \n {bidimensional_red_trans}")


El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.45 0.78 0.89 0.26]
 [0.84 0.18 0.65 0.58]
 [0.76 0.28 0.98 0.07]
 [0.4  0.39 0.79 0.54]
 [0.19 0.53 0.45 0.63]]
--------------------------

El array después de aplicar el método 'np.transpose()': 
 [[0.45 0.84 0.76 0.4  0.19]
 [0.78 0.18 0.28 0.39 0.53]
 [0.89 0.65 0.98 0.79 0.45]
 [0.26 0.58 0.07 0.54 0.63]]


#### Multidimensional

La cosa se complica cuando pasamos a *arrays* con más de dos dimensiones. 

Por defecto este método nos hará la siguiente transposicion:

- El número de columnas --> número de *arrays* 


- El número de filas --> número de filas


- El número de *arrays* --> número de columnas

In [82]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {tridimensional}")

# aplicamos el método 'np.transpose()' para ver que nos devuelve por defecto
print("--------------------------\n")
tridimensional_trans_defecto = np.transpose(tridimensional)
print(f"El array después de aplicar el método 'np.transpose()': \n {tridimensional_trans_defecto}")
# antes teníamos un array de 2 matrices x 3 filas x 5 columnas
# después tenemos un array de 5 matrices x 3 filas x 2 columnas

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[[39 62 83 33 74]
  [77 25 12 75 60]
  [30 13 73 14 72]]

 [[45 22 74 76 42]
  [20 34 75 30 14]
  [68 27 72 77 34]]]
--------------------------

El array después de aplicar el método 'np.transpose()': 
 [[[39 45]
  [77 20]
  [30 68]]

 [[62 22]
  [25 34]
  [13 27]]

 [[83 74]
  [12 75]
  [73 72]]

 [[33 76]
  [75 30]
  [14 77]]

 [[74 42]
  [60 14]
  [72 34]]]


Pero nosotras podemos especificar el sentido en el que queremos que transpongan los elementos de mi *array*

```python
np.transpose(nuestro_array, (1,2,0))
```

Entendiendo lo siguiente cuando definimos el siguiente *array*:

```python
multidimensional = np.random.randint(0,100, (2,3,5))
```

- 2 (posición 0): hace referencia a el número de *subarrays* o  matrices que queremos. 


- 3 (posición 1): hace referencia al número de filas que queremos en cada uno de nuestros *subarrays*.


- 5 (posición 2): hace referencia al número de columnas que queremos en cada uno de nuestros *subarrays*. 

> A este método le podemos pasar un parámetro adicional que puede ser una tupla o una lista donde indicaremos el orden de permutación que queremos

**¿Cómo lo hacemos?**

Lo haremos indicando donde queremos cada una de las posiciones antiguas. Es decir, imaginemos que queremos hacer la siguiente transposición:

- Las columnas (posición 2) queremos que sean las filas (posición 1)


- Las filas (posición 1) queremos que sean el número de *arrays* (posición 0)


- El número de *arrays* (posición 0) queremos que sean columnas (posición 2)

Lo único que tendremos que hacer es especificar este nuevo orden en el `transpose()`

```python
np.transpose(multidimensional, (1,2,0))
```

Si nos fijamos lo que hacemos en la tupla es, basándonos en las posiciones de la tupla:

- ¿Qué quiero en la posición 0 de la tupla (y por lo tanto de mi nuevo *array* transpuesto*? -- > lo que antes era la posición 1. Por lo tanto, pongo un 1


- ¿Qué quiero en la posción 1? --> lo que antes era la posición 2. Por lo tanto, pongo un 2



- ¿Qué quiero en la posición 2? --> lo que antes era la posición 0. Por lo tanto, pongo un 0

In [83]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {tridimensional}")

# aplicamos el método 'np.transpose()' para ver que nos devuelve por defecto
print("--------------------------\n")
tridimensional_trans_1 = np.transpose(tridimensional, (1,2,0))
print(f"El array después de aplicar el método 'np.transpose()': \n {tridimensional_trans_1}")
# antes teníamos un array de 2 matrices x 3 filas x 5 columnas
# después tenemos un array de 3 matrices x 5 filas x 2 columnas

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[[39 62 83 33 74]
  [77 25 12 75 60]
  [30 13 73 14 72]]

 [[45 22 74 76 42]
  [20 34 75 30 14]
  [68 27 72 77 34]]]
--------------------------

El array después de aplicar el método 'np.transpose()': 
 [[[39 45]
  [62 22]
  [83 74]
  [33 76]
  [74 42]]

 [[77 20]
  [25 34]
  [12 75]
  [75 30]
  [60 14]]

 [[30 68]
  [13 27]
  [73 72]
  [14 77]
  [72 34]]]


## `reshape()`:

`np.reshape` es una función de NumPy que se utiliza para cambiar la forma de un *array* sin cambiar sus datos subyacentes. Permite reorganizar los elementos de un *array* en una nueva forma especificada por el usuario.

La sintaxis básica de `np.reshape` es la siguiente:

```python
np.reshape(a, newshape, order='C')
```

Donde:
- `a`: Es la matriz que se desea remodelar.
- `newshape`: Es la nueva forma deseada de la matriz, especificada como una tupla de enteros.
- `order` (opciona): Especifica el orden en el que se deben leer los elementos de la matriz. Puede tomar dos valores: 'C' (por defecto) para leer los elementos en orden de fila (por filas) y 'F' para leer los elementos en orden de columna (por columnas).

In [84]:
# definimos un array unidimensional utilizando el método 'np.array()'
a = np.array([1, 2, 3, 4, 5, 6])
print(f"El array con el que vamos a trabajar es: \n {a}")

# Si queremos remodelar esta matriz en una matriz bidimensional 
# de 2 filas y 3 columnas, podemos usar `np.reshape` de la siguiente manera:
print("\n--------------------------\n")
reshaped_a = np.reshape(a, (2, 3))
print(f"El array después de aplicar el método 'np.reshape()' es: \n {reshaped_a}")


El array con el que vamos a trabajar es: 
 [1 2 3 4 5 6]

--------------------------

El array después de aplicar el método 'np.reshape()' es: 
 [[1 2 3]
 [4 5 6]]



También podemos utilizar `np.reshape` para remodelar *arrays* multidimensionales. Veamos un ejemplo:

In [85]:
# definimos un array unidimensional utilizando el método 'np.array()'
b = np.array([[1, 2, 3], [4, 5, 6]])
print(f"El array con el que vamos a trabajar es: \n {b}")

# Si queremos remodelar esta matriz en una matriz bidimensional 
# de 2 filas y 3 columnas, podemos usar `np.reshape` de la siguiente manera:
print("\n--------------------------\n")
reshaped_b = np.reshape(a, (6,))
print(f"El array después de aplicar el método 'np.reshape()' es: \n {reshaped_b}")

El array con el que vamos a trabajar es: 
 [[1 2 3]
 [4 5 6]]

--------------------------

El array después de aplicar el método 'np.reshape()' es: 
 [1 2 3 4 5 6]


## `np.swapaxes()`

El método `np.swapaxes` se utiliza para intercambiar dos ejes (dimensiones) específicos de un *array*. Permite reorganizar los ejes de un *array* sin cambiar los datos subyacentes.

La sintaxis básica de `np.swapaxes` es la siguiente:

```python
np.swapaxes(arr, axis1, axis2)
```

Donde:
- `arr` es la matriz en la que se desea intercambiar los ejes.
- `axis1` y `axis2` son los ejes que se deben intercambiar.

In [86]:
# definimos un array nuevo bidimensional
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"El array con el que vamos a trabajar es: \n {arr}")

# Si queremos intercambiar los ejes de este array, podemos usar `np.swapaxes` de la siguiente manera:
print("\n--------------------------\n")
swapped_arr = np.swapaxes(arr, 0, 1)
print(f"El array después de aplicar el método 'np.swapaxes()' es: {swapped_arr}")

El array con el que vamos a trabajar es: 
 [[1 2 3]
 [4 5 6]]

--------------------------

El array después de aplicar el método 'np.swapaxes()' es: [[1 4]
 [2 5]
 [3 6]]


In [87]:
# definimos un array nuevo tridimensional
arr_3d = np.array([[[1, 2, 3], [3, 4, 3]], [[5, 6, 4], [7, 8, 4]]])
print(f"El array con el que vamos a trabajar es: \n {arr_3d}")

# Si queremos intercambiar los ejes 0 (matrices) y 2 (columnas) de este array, podemos hacer lo siguiente:
print("\n--------------------------\n")
swapped_arr_3d = np.swapaxes(arr_3d, 0, 2)
print(f"El array después de aplicar el método 'np.swapaxes()' es: \n {swapped_arr_3d}")

El array con el que vamos a trabajar es: 
 [[[1 2 3]
  [3 4 3]]

 [[5 6 4]
  [7 8 4]]]

--------------------------

El array después de aplicar el método 'np.swapaxes()' es: 
 [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]

 [[3 4]
  [3 4]]]


En este caso, el eje 0 representaba las matrices individuales, el eje 1 representaba las filas y el eje 2 representaba las columnas. Después del intercambio, el eje 0 representa las columnas, el eje 1 representa las filas y el eje 2 representa las matrices individuales.
