In [3]:
import numpy as np

In [4]:
lista = [1,2,3,4,5]
array_unidimensional = np.array(lista)
print(array_unidimensional)

[1 2 3 4 5]


In [5]:
lista = ['1',2,3,4,5]
array_unidimensional = np.array(lista)
print(array_unidimensional)

['1' '2' '3' '4' '5']


In [6]:
lista = ['1',2,3,4,5]
array_unidimensional = np.array(lista, dtype= float)
print(array_unidimensional)

[1. 2. 3. 4. 5.]


In [7]:
lista = [[1,2,3],[4,5,6]]
array_biidimensional = np.array(lista)
print(array_biidimensional)

[[1 2 3]
 [4 5 6]]


In [8]:
array_tridimensional.shape ### forma
/ndim dimensiones 
/ size tamaño # numero de elementos

SyntaxError: incomplete input (431849867.py, line 3)

In [9]:
### genera numeros aleatorios
np.random.randint(1,17)


1

In [10]:
np.random.randint(1,17,3)


array([14, 16, 16], dtype=int32)

In [12]:
np.random.randint(1,17,(8,2))

array([[ 7, 12],
       [15, 16],
       [10,  8],
       [ 5,  1],
       [12, 13],
       [ 8, 13],
       [ 1, 15],
       [ 4,  1]], dtype=int32)

In [11]:
array_biidimensional

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
array_biidimensional[0]

array([1, 2, 3])

In [ ]:
array_tridimensional[0,: , 1] ### llama la matriz 0, ambas filas, elemento 1 de cada una

In [26]:
array_tri = np.random.randint(1,17,(3,2,4))
array_tri

array([[[10, 12, 11,  2],
        [15, 14, 14, 12]],

       [[ 7, 15,  2,  6],
        [ 9,  4,  6, 10]],

       [[ 7, 16,  8,  9],
        [ 8,  1, 14,  9]]], dtype=int32)

In [27]:
array_tri [2,1,:3] ### toma todas las matrices, la fila 0 y luego todas las columnas

array([ 8,  1, 14], dtype=int32)

In [21]:
var = 151+29
var= var/4
var

45.0

In [29]:
array_tri >10

array([[[False,  True,  True, False],
        [ True,  True,  True,  True]],

       [[False,  True, False, False],
        [False, False, False, False]],

       [[False,  True, False, False],
        [False, False,  True, False]]])

In [28]:
array_tri [array_tri >10] ### filtra la condicion de dentro de corchetes

array([12, 11, 15, 14, 14, 12, 15, 16, 14], dtype=int32)

In [31]:
array_tri [array_tri % 2 == 0] ### busca pares

array([10, 12,  2, 14, 14, 12,  2,  6,  4,  6, 10, 16,  8,  8, 14],
      dtype=int32)

In [34]:
array_tri [(array_tri > 10) & (array_tri % 2 == 0)] ### condiciones dentro de parentesis y usar & por and

array([12, 14, 14, 12, 16, 14], dtype=int32)

In [35]:
array_tri [(array_tri > 10) | (array_tri % 2 == 0)]

array([10, 12, 11,  2, 15, 14, 14, 12, 15,  2,  6,  4,  6, 10, 16,  8,  8,
       14], dtype=int32)

In [36]:
array_tri [(array_tri > 19) & (array_tri % 2 != 0)]

array([], dtype=int32)

In [38]:
array_tri

array([[[10, 12, 11,  2],
        [15, 14, 14, 12]],

       [[ 7, 15,  2,  6],
        [ 9,  4,  6, 10]],

       [[ 7, 16,  8,  9],
        [ 8,  1, 14,  9]]], dtype=int32)

In [37]:
np.where(array_tri > 10) ### devuelve los indices en vertical (matriz, linea, columna)

(array([0, 0, 0, 0, 0, 0, 1, 2, 2]),
 array([0, 0, 1, 1, 1, 1, 0, 0, 1]),
 array([1, 2, 0, 1, 2, 3, 1, 1, 2]))

In [39]:
np.transpose(array_tri)

array([[[10,  7,  7],
        [15,  9,  8]],

       [[12, 15, 16],
        [14,  4,  1]],

       [[11,  2,  8],
        [14,  6, 14]],

       [[ 2,  6,  9],
        [12, 10,  9]]], dtype=int32)

In [40]:
np.transpose(array_biidimensional)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
np.sum(array_tri)

np.int64(221)

In [ ]:
np.sum(array_tri, axis = 0) ### suma por matrices, las mismas posiciones